server:
  port: 8090

spring:
  datasource:
    driver-class-name: dm.jdbc.driver.DmDriver
    url:
    username:
    password:
    type: com.alibaba.druid.pool.DruidDataSource


  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8


mybatis:
  mapper-locations: classpath*:mapper/**/*.xml
  configuration:
    # 开启驼峰uName自动映射到u_name
    map-underscore-to-camel-case: true
    #    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    log-impl: org.apache.ibatis.logging.nologging.NoLoggingImpl
    cache-enabled: false
    call-setters-on-nulls: true
    jdbc-type-for-null: 'null'




logging:
  config: classpath:logback-spring-debug.xml
  level:
    root: info
  file:
    name: ./logs/log.log
  logback:
    logHome: ./logs
    groupParamHome: ./paramLogs


